### ISSUE TITLE
Furnaces after restart only lvl 1

### ISSUE THREAD

**Issue by Dartume** [TheVihara/SpedupFurnaces#1]
in both save optionen MySQL and sqlite is after a reboot of the server the Furnace from lvl x only lvl 1

**Comment by TheVihara** [comment]
Hey, Dartume

can you please provide me with more details on this situation? Please send me your server logs
and explain your situation more in detail. If you're bad at speaking english, you can use Google Translate,
which I believe will translate in a way that I'm going to be able to understand.

Please send me your server logs via Pastebin https://pastebin.com/

Thanks, Vihara

**Comment by Dartume** [comment]
I start my Server i give me a FURNACE with /spedupfurnace give FURNACE 1 1 Dartume, than i place it and level up to lvl 3.
I see in the MySQL Database it has save the FURNACE withe the coordinat and the level 3. Than i Restart the Server and the saved und updatet to lvl 3 FURNACE is now lvl 1. The plugin has not load the Database information.
https://pastebin.com/ZvReMskG

**Comment by TheVihara** [comment]
Hey, Dartume

I just tested my plugin with a MySql database and it worked perfectly fine. The furnace level was still the same after restart. I don't know what's wrong on your part but I just finished recoding the storing system, you can download the new latest version of SpedupFurnaces from https://www.spigotmc.org/resources/spedup-furnaces.108326/ and see if that fixes the issue.

Regards, Vihara

**Comment by Dartume** [comment]
[22.03 13:52:17.708] INFO: [CityBuild-1] [13:52:17 WARN]: [SpedupFurnaces] Plugin SpedupFurnaces v1.0.2.0-BETA generated an exception while executing task 40
[22.03 13:52:17.708] INFO: [CityBuild-1] java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getName()" because the return value of "org.bukkit.Location.getWorld()" is null
[22.03 13:52:17.708] INFO: [CityBuild-1]        at me.gorenjec.spedupfurnaces.storage.SQLStorage.updateFurnace(SQLStorage.java:133) ~[SpedupFurnaces-1.0.2.0-BETA-all.jar:?]
[22.03 13:52:17.708] INFO: [CityBuild-1]        at me.gorenjec.spedupfurnaces.cache.InMemoryCache.lambda$flush$0(InMemoryCache.java:44) ~[SpedupFurnaces-1.0.2.0-BETA-all.jar:?]
[22.03 13:52:17.708] INFO: [CityBuild-1]        at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
[22.03 13:52:17.708] INFO: [CityBuild-1]        at me.gorenjec.spedupfurnaces.cache.InMemoryCache.flush(InMemoryCache.java:43) ~[SpedupFurnaces-1.0.2.0-BETA-all.jar:?]
[22.03 13:52:17.708] INFO: [CityBuild-1]        at me.gorenjec.spedupfurnaces.cache.InMemoryCache$1.run(InMemoryCache.java:62) ~[SpedupFurnaces-1.0.2.0-BETA-all.jar:?]
[22.03 13:52:17.708] INFO: [CityBuild-1]        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1858]
[22.03 13:52:17.708] INFO: [CityBuild-1]        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1858]
[22.03 13:52:17.708] INFO: [CityBuild-1]        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
[22.03 13:52:17.708] INFO: [CityBuild-1]        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
[22.03 13:52:17.708] INFO: [CityBuild-1]        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
[22.03 13:52:17.708] INFO: [CityBuild-1]        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Dartume** [comment]
with SQL
[14:18:54] [Craft Scheduler Thread - 8 - SpedupFurnaces/WARN]: [SpedupFurnaces] Plugin SpedupFurnaces v1.0.2.0-BETA generated an exception while executing task 45
java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getName()" because the return value of "org.bukkit.Location.getWorld()" is null
	at me.gorenjec.spedupfurnaces.storage.SQLStorage.updateFurnace(SQLStorage.java:133) ~[SpedupFurnaces-1.0.2.0-BETA-all.jar:?]
	at me.gorenjec.spedupfurnaces.cache.InMemoryCache.lambda$flush$0(InMemoryCache.java:44) ~[SpedupFurnaces-1.0.2.0-BETA-all.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at me.gorenjec.spedupfurnaces.cache.InMemoryCache.flush(InMemoryCache.java:43) ~[SpedupFurnaces-1.0.2.0-BETA-all.jar:?]
	at me.gorenjec.spedupfurnaces.cache.InMemoryCache$1.run(InMemoryCache.java:62) ~[SpedupFurnaces-1.0.2.0-BETA-all.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by TheVihara** [comment]
My plugin only provides support for versions 1.19.3 and 1.19.4. Please upgrade your server version asap, your server is at risk because of security bugs, .. that have been patched int he latest versions.
